# Azure Blob Storage Configuration
azure:
  account: "mwbetaazureeastus"
  access_key: "PdNPJEDb/pjOQjKmqd3V4dR58Pc2lQM1TzGSD6ct5r1xkxifsywFypKHLNEdqjjthzeZfrOO2wY6+ASt+o5wUw=="
  # The URI provided: azure://mwbetaazureeastus-log-index/indexes
  # This translates to:
  # container: "mwbetaazureeastus-log-index"
  # path_prefix: "indexes/"
  container: "mwbetaazureeastus-log-index"
  path_prefix: "indexes/"

# Polling configuration
polling:
  # The duration to wait between polls, in seconds.
  duration_seconds: 300 # e.g., 5 minutes